/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.crystopher.calculadora.View;

import br.com.crystopher.calculadora.model.CalculadoraModel;

/**
 *
 * @author Crystopher
 */
public class CalculadoraView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(CalculadoraView.class.getName());

    CalculadoraModel calculadora = new CalculadoraModel();
    boolean segundoValor = false;
    String operacao;

    public CalculadoraView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2Numero = new javax.swing.JLabel();
        jButtonClear1 = new javax.swing.JButton();
        jButtonPorcentagem1 = new javax.swing.JButton();
        jButtonDivi1 = new javax.swing.JButton();
        jButtonMultiplica1 = new javax.swing.JButton();
        jButtonMenos = new javax.swing.JButton();
        jButtonMais = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonPonto = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2Numero.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 60)); // NOI18N
        jLabel2Numero.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2Numero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel2Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 360, 120));

        jButtonClear1.setContentAreaFilled(false);
        jButtonClear1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClear1.addActionListener(this::jButtonClear1ActionPerformed);
        getContentPane().add(jButtonClear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 80, 90));

        jButtonPorcentagem1.setContentAreaFilled(false);
        jButtonPorcentagem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPorcentagem1.addActionListener(this::jButtonPorcentagem1ActionPerformed);
        getContentPane().add(jButtonPorcentagem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 80, 90));

        jButtonDivi1.setContentAreaFilled(false);
        jButtonDivi1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDivi1.addActionListener(this::jButtonDivi1ActionPerformed);
        getContentPane().add(jButtonDivi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 80, 90));

        jButtonMultiplica1.setContentAreaFilled(false);
        jButtonMultiplica1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMultiplica1.addActionListener(this::jButtonMultiplica1ActionPerformed);
        getContentPane().add(jButtonMultiplica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 90, 90));

        jButtonMenos.setContentAreaFilled(false);
        jButtonMenos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMenos.addActionListener(this::jButtonMenosActionPerformed);
        getContentPane().add(jButtonMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 90, 80));

        jButtonMais.setContentAreaFilled(false);
        jButtonMais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMais.addActionListener(this::jButtonMaisActionPerformed);
        getContentPane().add(jButtonMais, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 90, 80));

        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(this::jButton9ActionPerformed);
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 80, 80));

        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(this::jButton8ActionPerformed);
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 80, 80));

        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(this::jButton7ActionPerformed);
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 80, 80));

        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(this::jButton6ActionPerformed);
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 80, 80));

        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(this::jButton5ActionPerformed);
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 80, 80));

        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(this::jButton4ActionPerformed);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 80, 80));

        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 80, 80));

        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 80, 80));

        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 80, 80));

        jButton0.setContentAreaFilled(false);
        jButton0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton0.addActionListener(this::jButton0ActionPerformed);
        getContentPane().add(jButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 80, 80));

        jButtonPonto.setContentAreaFilled(false);
        jButtonPonto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPonto.addActionListener(this::jButtonPontoActionPerformed);
        getContentPane().add(jButtonPonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 650, 80, 80));

        jButtonApagar.setContentAreaFilled(false);
        jButtonApagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonApagar.addActionListener(this::jButtonApagarActionPerformed);
        getContentPane().add(jButtonApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 650, 80, 80));

        jButtonIgual.setContentAreaFilled(false);
        jButtonIgual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonIgual.addActionListener(this::jButtonIgualActionPerformed);
        getContentPane().add(jButtonIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 80, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/calculadora.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jLabel2Numero.setText(jLabel2Numero.getText() + "7");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButtonClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClear1ActionPerformed
        calculadora.setValor1(0);
        calculadora.setValor2(0);
        segundoValor = false;
        jLabel2Numero.setText("");
        operacao = "";
    }//GEN-LAST:event_jButtonClear1ActionPerformed

    private void jButtonPorcentagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPorcentagem1ActionPerformed
        calculadora.setValor1(Double.parseDouble(jLabel2Numero.getText()));
        calculadora.setResultado(calculadora.getValor1() / 100);
        jLabel2Numero.setText(String.valueOf(calculadora.getResultado()));
    }//GEN-LAST:event_jButtonPorcentagem1ActionPerformed

    private void jButtonDivi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivi1ActionPerformed
        calculadora.setValor1(Double.parseDouble(jLabel2Numero.getText()));
        segundoValor = true;
        jLabel2Numero.setText("");
        operacao = "divisao";
    }//GEN-LAST:event_jButtonDivi1ActionPerformed

    private void jButtonMultiplica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplica1ActionPerformed
        calculadora.setValor1(Double.parseDouble(jLabel2Numero.getText()));
        segundoValor = true;
        jLabel2Numero.setText("");
        operacao = "multiplicacao";
    }//GEN-LAST:event_jButtonMultiplica1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jLabel2Numero.setText(jLabel2Numero.getText() + "8");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jLabel2Numero.setText(jLabel2Numero.getText() + "9");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosActionPerformed
        calculadora.setValor1(Double.parseDouble(jLabel2Numero.getText()));
        segundoValor = true;
        jLabel2Numero.setText("");
        operacao = "subtracao";
    }//GEN-LAST:event_jButtonMenosActionPerformed

    private void jButtonMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaisActionPerformed
        calculadora.setValor1(Double.parseDouble(jLabel2Numero.getText()));
        segundoValor = true;
        jLabel2Numero.setText("");
        operacao = "soma";
    }//GEN-LAST:event_jButtonMaisActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jLabel2Numero.setText(jLabel2Numero.getText() + "4");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jLabel2Numero.setText(jLabel2Numero.getText() + "5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jLabel2Numero.setText(jLabel2Numero.getText() + "6");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel2Numero.setText(jLabel2Numero.getText() + "1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel2Numero.setText(jLabel2Numero.getText() + "2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jLabel2Numero.setText(jLabel2Numero.getText() + "3");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        jLabel2Numero.setText(jLabel2Numero.getText() + "0");
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPontoActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        jLabel2Numero.setText(jLabel2Numero.getText().substring(0, jLabel2Numero.getText().length() - 1));
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed
        if (segundoValor == true) {
            calculadora.setValor2(Double.parseDouble(jLabel2Numero.getText()));
            if (operacao == "soma") {
                calculadora.somar();
                jLabel2Numero.setText(String.valueOf(calculadora.getResultado()));
                operacao = "";
            }
             if (operacao == "subtracao") {
                calculadora.subtracao();
                jLabel2Numero.setText(String.valueOf(calculadora.getResultado()));
                operacao = "";
            }
              if (operacao == "divisao") {
                calculadora.divisao();
                jLabel2Numero.setText(String.valueOf(calculadora.getResultado()));
                operacao = "";
            }
               if (operacao == "multiplicacao") {
                calculadora.multiplicacao();
                jLabel2Numero.setText(String.valueOf(calculadora.getResultado()));
                operacao = "";
            }
        }
    }//GEN-LAST:event_jButtonIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonClear1;
    private javax.swing.JButton jButtonDivi1;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonMais;
    private javax.swing.JButton jButtonMenos;
    private javax.swing.JButton jButtonMultiplica1;
    private javax.swing.JButton jButtonPonto;
    private javax.swing.JButton jButtonPorcentagem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2Numero;
    // End of variables declaration//GEN-END:variables
}
